### ISSUE TITLE
[Windows] Improve language fallback

### ISSUE THREAD

**Issue by ecodiv** [ransome1/sleek#95]
**Is it an actual bug?**
Yes, it is an error message, and sleek is not functioning

**Did you check if the bug has already been reported?**
Yes, a similar bug was reported for the flatpack version, which was reportedly solved

**Describe the bug**
Trying to start Sleek on Windows (downloaded from Github, I am getting a _JavaScript error occurred in the main process_ error message, see attached screenshot. 

Sleek starts nonetheless, but I cannot open todo.txt files (selecting one does nothing).

**To Reproduce**
1. Download Sleek 0.9.9 and double click
2. Sleek will start, with separate window with above-mentioned error message
3. Close error message and try to open todo.txt file

**Do you see any error entries in sleeks developer tools?**
Ctrl + Shift + I does not open the developer tools.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7816789/114353738-a95b3700-9b6d-11eb-83eb-20c23792e316.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version of sleek 0.9.9
 - Source: Github

**Comment by ransome1** [comment]
Hi @ecodiv. Thanks for the report. I downloaded the .exe from Github and started it up on Windows 10. So far I cannot see any errors. 

When you have sleek open, can you please press the Alt key, which will open up the top menu, and select the developer tools in the "About" tab? Within the dev tools please select the "Console" tab and check for any error entries that appear, when you fail to open a file.

Also I uploaded the 0.9.9 that contains a couple of work on the way to v1.0. Please feel free to check if this issue persists: https://github.com/ransome1/sleek/releases/download/v0.9.9/sleek.0.9.9.exe

**Comment by ecodiv** [comment]
These are the errors I can see in the Console, related to at least two different actions I think? (1) open a file, and (2) add a task.

`Uncaught (in promise) Error in generateTableRow(): TypeError: Cannot read property 'done' of undefined: RENDER.JS:1188`
`Uncaught (in promise) Error in showForm(): TypeError: Cannot read property 'addTodo' of undefined: RENDER.JS:404`
```
Uncaught ReferenceError: translations is not defined
    at toggleInputSize (render.js:2086)
    at HTMLAnchorElement.modalFormInputResize.onclick (render.js:2366)
```

**Comment by ransome1** [comment]
@ecodiv, interesting, for whatsoever reason sleek cannot load the translations.

Can you please check sleeks config file? On my Windows VM it is located at "C:\Users\User\AppData\sleek\user-preferences.json". I wonder what the "language" entry says, can you share it or even the whole config? You can send it to me ransome@uber.space

Also you can rename the "sleek" folder in your AppData folder and restart sleek. If it is a problem with the config file, this might solve it. You will start with a fresh sleek though.

**Comment by ecodiv** [comment]
It says `"language":"nl"`. Changing that to `"language":"en"` did the trick. It works like a charm now :-).

**Comment by ransome1** [comment]
That is good to hear, but wasn't suppose to happen ;) 

As dutch is not yet supported it should have fallen back to english. I'll investigate on it.

If you would like to use sleek in dutch, you can easily translate it and share your translations. So if you ever find some time, I'll be happy to guide you on how to do it.

**Comment by ecodiv** [comment]
I actually prefer my software in English, but is is a work computer, so I cannot change the system language. But, if I find time, I will see if I can contribute a translation

**Comment by ransome1** [comment]
Hi @ecodiv, I added a fix for this issue in v1.0.0-Alpha. Can I ask you for a quick support testing this?

https://github.com/ransome1/sleek/releases/tag/v1.0.0-Alpha

Could you please delete or rename your config folder and start up the Alpha release? I'm curious if the fallback to english is working in your production environment or if we still see the error.

**Comment by ecodiv** [comment]
Hi @ransome1 tried out v1.0.0 (after deleting the config folder, and it now works out of the box.. so the fallback works :-) Thanks!

**Comment by ransome1** [comment]
Thanks for your feedback!
